### ISSUE TITLE
Using Box for run_instruction

### ISSUE THREAD

**Issue by emoon** [brunodea/gebemula#7]
Hi,

I looked at the code and in `src/cpu/cpu.rs` 

``` Rust
pub fn run_instruction(...) -> Box<Instruction> {
  ...
}
```

`Box<...>` is being used. I wonder what the reason for that is? Box will allocate memory on the heap for each executed instruction and will add a bit of extra overhead. In this case (unless I have missed something) just returning the Instruction by value (and thus on the stack instead) should work just as fine.

**Comment by brunodea** [comment]
Hey @emoon, thanks for stopping by! You definitely didn't miss anything, for some reason I thought returing Box<T> would be faster than copying the Instruction.

Returning the Box<T> was added in one of the latests commits as of now and I didn't realize it was much slower because of that. Anyway, thanks for that, I'll fix it!

**Comment by emoon** [comment]
np :)

**Comment by emoon** [comment]
Also in your previous version you do `inst.clone()` I really don't think that is needed. Something like this works fine

``` Rust
struct Instruction {
    some_data: u32,
}

fn run_instruction() -> Instruction {
    let inst = Instruction { some_data: 42 };
    inst
}

fn main(){
    let instruction = run_instruction();
    println!("{}", instruction.some_data);
}
```

**Comment by brunodea** [comment]
@emoon once again, thank you! I also realized that and did as you suggested :)

**Comment by emoon** [comment]
np :)
